// Package ovh generates Terraform configurations for OVHcloud deployments.
package ovh

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/homeport/homeport/internal/domain/generator"
	"github.com/homeport/homeport/internal/domain/mapper"
)

// generateNetworkingTF generates networking.tf for OVH private networks and load balancers.
func (g *Generator) generateNetworkingTF(networking, loadBalancers []*mapper.MappingResult, config *generator.TargetConfig) string {
	var buf bytes.Buffer

	buf.WriteString("# OVH Networking Resources\n")
	buf.WriteString("# Generated by Homeport\n\n")

	region := getRegion(config)

	// Generate base private network
	g.generatePrivateNetwork(&buf, config, region)

	// Generate security groups
	g.generateSecurityGroups(&buf, config)

	// Generate load balancers
	if len(loadBalancers) > 0 || config.HALevel.RequiresMultiServer() {
		buf.WriteString("# ═══════════════════════════════════════════════════════════════════════════\n")
		buf.WriteString("# Load Balancers (OpenStack Octavia)\n")
		buf.WriteString("# ═══════════════════════════════════════════════════════════════════════════\n\n")

		if len(loadBalancers) > 0 {
			for _, res := range loadBalancers {
				g.generateLoadBalancerResource(&buf, res, config, region)
			}
		} else if config.HALevel.RequiresMultiServer() {
			// Create default load balancer for HA
			g.generateDefaultLoadBalancer(&buf, config, region)
		}
	}

	// Generate floating IPs for public access
	g.generateFloatingIPs(&buf, config, region)

	return buf.String()
}

// generatePrivateNetwork generates the base private network infrastructure.
func (g *Generator) generatePrivateNetwork(buf *bytes.Buffer, config *generator.TargetConfig, region string) {
	buf.WriteString("# ═══════════════════════════════════════════════════════════════════════════\n")
	buf.WriteString("# Private Network (vRack)\n")
	buf.WriteString("# ═══════════════════════════════════════════════════════════════════════════\n\n")

	// Private network
	buf.WriteString("resource \"openstack_networking_network_v2\" \"main\" {\n")
	buf.WriteString("  name           = \"${var.project_name}-network\"\n")
	buf.WriteString("  admin_state_up = true\n\n")
	buf.WriteString("  # Note: For vRack integration, configure via OVH Manager\n")
	buf.WriteString("}\n\n")

	// Subnet
	buf.WriteString("resource \"openstack_networking_subnet_v2\" \"main\" {\n")
	buf.WriteString("  name       = \"${var.project_name}-subnet\"\n")
	buf.WriteString("  network_id = openstack_networking_network_v2.main.id\n")
	buf.WriteString("  cidr       = \"10.0.0.0/16\"\n")
	buf.WriteString("  ip_version = 4\n\n")

	buf.WriteString("  allocation_pool {\n")
	buf.WriteString("    start = \"10.0.1.10\"\n")
	buf.WriteString("    end   = \"10.0.255.254\"\n")
	buf.WriteString("  }\n\n")

	buf.WriteString("  dns_nameservers = [\n")
	buf.WriteString("    \"213.186.33.99\",  # OVH DNS\n")
	buf.WriteString("    \"8.8.8.8\",\n")
	buf.WriteString("  ]\n\n")

	buf.WriteString("  enable_dhcp = true\n")
	buf.WriteString("}\n\n")

	// Router for external connectivity
	buf.WriteString("# Router for external network access\n")
	buf.WriteString("data \"openstack_networking_network_v2\" \"ext_net\" {\n")
	buf.WriteString("  name = \"Ext-Net\"\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_networking_router_v2\" \"main\" {\n")
	buf.WriteString("  name                = \"${var.project_name}-router\"\n")
	buf.WriteString("  admin_state_up      = true\n")
	buf.WriteString("  external_network_id = data.openstack_networking_network_v2.ext_net.id\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_networking_router_interface_v2\" \"main\" {\n")
	buf.WriteString("  router_id = openstack_networking_router_v2.main.id\n")
	buf.WriteString("  subnet_id = openstack_networking_subnet_v2.main.id\n")
	buf.WriteString("}\n\n")

	// Additional subnets for HA deployments
	if config.HALevel.RequiresMultiServer() {
		buf.WriteString("# Additional subnet for HA deployment\n")
		buf.WriteString("resource \"openstack_networking_subnet_v2\" \"secondary\" {\n")
		buf.WriteString("  name       = \"${var.project_name}-subnet-secondary\"\n")
		buf.WriteString("  network_id = openstack_networking_network_v2.main.id\n")
		buf.WriteString("  cidr       = \"10.1.0.0/16\"\n")
		buf.WriteString("  ip_version = 4\n\n")

		buf.WriteString("  allocation_pool {\n")
		buf.WriteString("    start = \"10.1.1.10\"\n")
		buf.WriteString("    end   = \"10.1.255.254\"\n")
		buf.WriteString("  }\n\n")

		buf.WriteString("  dns_nameservers = [\n")
		buf.WriteString("    \"213.186.33.99\",\n")
		buf.WriteString("    \"8.8.8.8\",\n")
		buf.WriteString("  ]\n")
		buf.WriteString("}\n\n")

		buf.WriteString("resource \"openstack_networking_router_interface_v2\" \"secondary\" {\n")
		buf.WriteString("  router_id = openstack_networking_router_v2.main.id\n")
		buf.WriteString("  subnet_id = openstack_networking_subnet_v2.secondary.id\n")
		buf.WriteString("}\n\n")
	}
}

// generateSecurityGroups generates network security groups.
func (g *Generator) generateSecurityGroups(buf *bytes.Buffer, config *generator.TargetConfig) {
	buf.WriteString("# ═══════════════════════════════════════════════════════════════════════════\n")
	buf.WriteString("# Security Groups\n")
	buf.WriteString("# ═══════════════════════════════════════════════════════════════════════════\n\n")

	// Web security group
	buf.WriteString("resource \"openstack_networking_secgroup_v2\" \"web\" {\n")
	buf.WriteString("  name        = \"${var.project_name}-web-sg\"\n")
	buf.WriteString("  description = \"Security group for web traffic\"\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_networking_secgroup_rule_v2\" \"web_http\" {\n")
	buf.WriteString("  direction         = \"ingress\"\n")
	buf.WriteString("  ethertype         = \"IPv4\"\n")
	buf.WriteString("  protocol          = \"tcp\"\n")
	buf.WriteString("  port_range_min    = 80\n")
	buf.WriteString("  port_range_max    = 80\n")
	buf.WriteString("  remote_ip_prefix  = \"0.0.0.0/0\"\n")
	buf.WriteString("  security_group_id = openstack_networking_secgroup_v2.web.id\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_networking_secgroup_rule_v2\" \"web_https\" {\n")
	buf.WriteString("  direction         = \"ingress\"\n")
	buf.WriteString("  ethertype         = \"IPv4\"\n")
	buf.WriteString("  protocol          = \"tcp\"\n")
	buf.WriteString("  port_range_min    = 443\n")
	buf.WriteString("  port_range_max    = 443\n")
	buf.WriteString("  remote_ip_prefix  = \"0.0.0.0/0\"\n")
	buf.WriteString("  security_group_id = openstack_networking_secgroup_v2.web.id\n")
	buf.WriteString("}\n\n")

	// Database security group
	buf.WriteString("resource \"openstack_networking_secgroup_v2\" \"database\" {\n")
	buf.WriteString("  name        = \"${var.project_name}-db-sg\"\n")
	buf.WriteString("  description = \"Security group for database access\"\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_networking_secgroup_rule_v2\" \"db_postgres\" {\n")
	buf.WriteString("  direction         = \"ingress\"\n")
	buf.WriteString("  ethertype         = \"IPv4\"\n")
	buf.WriteString("  protocol          = \"tcp\"\n")
	buf.WriteString("  port_range_min    = 5432\n")
	buf.WriteString("  port_range_max    = 5432\n")
	buf.WriteString("  remote_ip_prefix  = \"10.0.0.0/8\"\n")
	buf.WriteString("  security_group_id = openstack_networking_secgroup_v2.database.id\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_networking_secgroup_rule_v2\" \"db_mysql\" {\n")
	buf.WriteString("  direction         = \"ingress\"\n")
	buf.WriteString("  ethertype         = \"IPv4\"\n")
	buf.WriteString("  protocol          = \"tcp\"\n")
	buf.WriteString("  port_range_min    = 3306\n")
	buf.WriteString("  port_range_max    = 3306\n")
	buf.WriteString("  remote_ip_prefix  = \"10.0.0.0/8\"\n")
	buf.WriteString("  security_group_id = openstack_networking_secgroup_v2.database.id\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_networking_secgroup_rule_v2\" \"db_redis\" {\n")
	buf.WriteString("  direction         = \"ingress\"\n")
	buf.WriteString("  ethertype         = \"IPv4\"\n")
	buf.WriteString("  protocol          = \"tcp\"\n")
	buf.WriteString("  port_range_min    = 6379\n")
	buf.WriteString("  port_range_max    = 6379\n")
	buf.WriteString("  remote_ip_prefix  = \"10.0.0.0/8\"\n")
	buf.WriteString("  security_group_id = openstack_networking_secgroup_v2.database.id\n")
	buf.WriteString("}\n\n")

	// Internal security group (allow all internal traffic)
	buf.WriteString("resource \"openstack_networking_secgroup_v2\" \"internal\" {\n")
	buf.WriteString("  name        = \"${var.project_name}-internal-sg\"\n")
	buf.WriteString("  description = \"Security group for internal traffic\"\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_networking_secgroup_rule_v2\" \"internal_all\" {\n")
	buf.WriteString("  direction         = \"ingress\"\n")
	buf.WriteString("  ethertype         = \"IPv4\"\n")
	buf.WriteString("  protocol          = \"tcp\"\n")
	buf.WriteString("  port_range_min    = 1\n")
	buf.WriteString("  port_range_max    = 65535\n")
	buf.WriteString("  remote_ip_prefix  = \"10.0.0.0/8\"\n")
	buf.WriteString("  security_group_id = openstack_networking_secgroup_v2.internal.id\n")
	buf.WriteString("}\n\n")
}

// generateLoadBalancerResource generates a load balancer from source resource.
func (g *Generator) generateLoadBalancerResource(buf *bytes.Buffer, res *mapper.MappingResult, config *generator.TargetConfig, region string) {
	name := sanitizeName(res.SourceResource.Name)

	// Comment with source resource info
	buf.WriteString(fmt.Sprintf("# Source: %s (%s)\n", res.SourceResource.Type, res.SourceResource.Name))

	// Load balancer
	buf.WriteString(fmt.Sprintf("resource \"openstack_lb_loadbalancer_v2\" \"%s\" {\n", name))
	buf.WriteString(fmt.Sprintf("  name          = \"${var.project_name}-%s\"\n", name))
	buf.WriteString("  vip_subnet_id = openstack_networking_subnet_v2.main.id\n")
	buf.WriteString("  admin_state_up = true\n\n")
	buf.WriteString("  tags = [\n")
	buf.WriteString("    \"managed-by:homeport\",\n")
	buf.WriteString("    \"project:${var.project_name}\",\n")
	buf.WriteString("  ]\n")
	buf.WriteString("}\n\n")

	// Listener for HTTP
	buf.WriteString(fmt.Sprintf("resource \"openstack_lb_listener_v2\" \"%s_http\" {\n", name))
	buf.WriteString(fmt.Sprintf("  name            = \"%s-http\"\n", name))
	buf.WriteString("  protocol        = \"HTTP\"\n")
	buf.WriteString("  protocol_port   = 80\n")
	buf.WriteString(fmt.Sprintf("  loadbalancer_id = openstack_lb_loadbalancer_v2.%s.id\n", name))
	buf.WriteString("  admin_state_up  = true\n")
	buf.WriteString("}\n\n")

	// Listener for HTTPS
	buf.WriteString(fmt.Sprintf("resource \"openstack_lb_listener_v2\" \"%s_https\" {\n", name))
	buf.WriteString(fmt.Sprintf("  name            = \"%s-https\"\n", name))
	buf.WriteString("  protocol        = \"HTTPS\"\n")
	buf.WriteString("  protocol_port   = 443\n")
	buf.WriteString(fmt.Sprintf("  loadbalancer_id = openstack_lb_loadbalancer_v2.%s.id\n", name))
	buf.WriteString("  admin_state_up  = true\n\n")
	buf.WriteString("  # Note: Configure SSL certificate via OVH Manager or API\n")
	buf.WriteString("}\n\n")

	// Pool for HTTP
	buf.WriteString(fmt.Sprintf("resource \"openstack_lb_pool_v2\" \"%s_http_pool\" {\n", name))
	buf.WriteString(fmt.Sprintf("  name        = \"%s-http-pool\"\n", name))
	buf.WriteString("  protocol    = \"HTTP\"\n")
	buf.WriteString("  lb_method   = \"ROUND_ROBIN\"\n")
	buf.WriteString(fmt.Sprintf("  listener_id = openstack_lb_listener_v2.%s_http.id\n", name))
	buf.WriteString("}\n\n")

	// Pool for HTTPS
	buf.WriteString(fmt.Sprintf("resource \"openstack_lb_pool_v2\" \"%s_https_pool\" {\n", name))
	buf.WriteString(fmt.Sprintf("  name        = \"%s-https-pool\"\n", name))
	buf.WriteString("  protocol    = \"HTTPS\"\n")
	buf.WriteString("  lb_method   = \"ROUND_ROBIN\"\n")
	buf.WriteString(fmt.Sprintf("  listener_id = openstack_lb_listener_v2.%s_https.id\n", name))
	buf.WriteString("}\n\n")

	// Health monitor
	buf.WriteString(fmt.Sprintf("resource \"openstack_lb_monitor_v2\" \"%s_monitor\" {\n", name))
	buf.WriteString(fmt.Sprintf("  name        = \"%s-monitor\"\n", name))
	buf.WriteString(fmt.Sprintf("  pool_id     = openstack_lb_pool_v2.%s_http_pool.id\n", name))
	buf.WriteString("  type        = \"HTTP\"\n")
	buf.WriteString("  delay       = 10\n")
	buf.WriteString("  timeout     = 5\n")
	buf.WriteString("  max_retries = 3\n")
	buf.WriteString("  http_method = \"GET\"\n")
	buf.WriteString("  url_path    = \"/health\"\n")
	buf.WriteString("  expected_codes = \"200\"\n")
	buf.WriteString("}\n\n")

	// Floating IP for the load balancer
	buf.WriteString(fmt.Sprintf("resource \"openstack_networking_floatingip_v2\" \"%s_fip\" {\n", name))
	buf.WriteString("  pool = \"Ext-Net\"\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("resource \"openstack_networking_floatingip_associate_v2\" \"%s_fip_assoc\" {\n", name))
	buf.WriteString(fmt.Sprintf("  floating_ip = openstack_networking_floatingip_v2.%s_fip.address\n", name))
	buf.WriteString(fmt.Sprintf("  port_id     = openstack_lb_loadbalancer_v2.%s.vip_port_id\n", name))
	buf.WriteString("}\n\n")
}

// generateDefaultLoadBalancer generates a default load balancer for HA configurations.
func (g *Generator) generateDefaultLoadBalancer(buf *bytes.Buffer, config *generator.TargetConfig, region string) {
	buf.WriteString("# Default Load Balancer for HA\n")

	buf.WriteString("resource \"openstack_lb_loadbalancer_v2\" \"main\" {\n")
	buf.WriteString("  name          = \"${var.project_name}-lb\"\n")
	buf.WriteString("  vip_subnet_id = openstack_networking_subnet_v2.main.id\n")
	buf.WriteString("  admin_state_up = true\n\n")
	buf.WriteString("  tags = [\n")
	buf.WriteString("    \"managed-by:homeport\",\n")
	buf.WriteString("    \"project:${var.project_name}\",\n")
	buf.WriteString("  ]\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_lb_listener_v2\" \"http\" {\n")
	buf.WriteString("  name            = \"http\"\n")
	buf.WriteString("  protocol        = \"HTTP\"\n")
	buf.WriteString("  protocol_port   = 80\n")
	buf.WriteString("  loadbalancer_id = openstack_lb_loadbalancer_v2.main.id\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_lb_listener_v2\" \"https\" {\n")
	buf.WriteString("  name            = \"https\"\n")
	buf.WriteString("  protocol        = \"TERMINATED_HTTPS\"\n")
	buf.WriteString("  protocol_port   = 443\n")
	buf.WriteString("  loadbalancer_id = openstack_lb_loadbalancer_v2.main.id\n\n")
	buf.WriteString("  # SSL certificate - configure via OVH API\n")
	buf.WriteString("  # default_tls_container_ref = \"\"\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_lb_pool_v2\" \"main\" {\n")
	buf.WriteString("  name        = \"main-pool\"\n")
	buf.WriteString("  protocol    = \"HTTP\"\n")
	buf.WriteString("  lb_method   = \"ROUND_ROBIN\"\n")
	buf.WriteString("  listener_id = openstack_lb_listener_v2.http.id\n\n")

	buf.WriteString("  persistence {\n")
	buf.WriteString("    type        = \"APP_COOKIE\"\n")
	buf.WriteString("    cookie_name = \"SERVERID\"\n")
	buf.WriteString("  }\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_lb_monitor_v2\" \"main\" {\n")
	buf.WriteString("  name        = \"main-monitor\"\n")
	buf.WriteString("  pool_id     = openstack_lb_pool_v2.main.id\n")
	buf.WriteString("  type        = \"HTTP\"\n")
	buf.WriteString("  delay       = 10\n")
	buf.WriteString("  timeout     = 5\n")
	buf.WriteString("  max_retries = 3\n")
	buf.WriteString("  url_path    = \"/health\"\n")
	buf.WriteString("}\n\n")

	// Public IP for load balancer
	buf.WriteString("resource \"openstack_networking_floatingip_v2\" \"lb\" {\n")
	buf.WriteString("  pool = \"Ext-Net\"\n")
	buf.WriteString("}\n\n")

	buf.WriteString("resource \"openstack_networking_floatingip_associate_v2\" \"lb\" {\n")
	buf.WriteString("  floating_ip = openstack_networking_floatingip_v2.lb.address\n")
	buf.WriteString("  port_id     = openstack_lb_loadbalancer_v2.main.vip_port_id\n")
	buf.WriteString("}\n\n")
}

// generateFloatingIPs generates floating IPs for public access.
func (g *Generator) generateFloatingIPs(buf *bytes.Buffer, config *generator.TargetConfig, region string) {
	// Only for non-HA (single instance) or explicit public access needs
	if !config.HALevel.RequiresMultiServer() {
		buf.WriteString("# ═══════════════════════════════════════════════════════════════════════════\n")
		buf.WriteString("# Floating IPs (Public IP addresses)\n")
		buf.WriteString("# ═══════════════════════════════════════════════════════════════════════════\n\n")

		buf.WriteString("# Floating IP for primary instance\n")
		buf.WriteString("resource \"openstack_networking_floatingip_v2\" \"primary\" {\n")
		buf.WriteString("  pool = \"Ext-Net\"\n")
		buf.WriteString("}\n\n")

		buf.WriteString("# Associate with primary compute instance\n")
		buf.WriteString("# resource \"openstack_compute_floatingip_associate_v2\" \"primary\" {\n")
		buf.WriteString("#   floating_ip = openstack_networking_floatingip_v2.primary.address\n")
		buf.WriteString("#   instance_id = openstack_compute_instance_v2.INSTANCE_NAME.id\n")
		buf.WriteString("# }\n\n")
	}
}

// mapToOVHLoadBalancerType maps source LB type to OVH configuration.
func mapToOVHLoadBalancerType(res *mapper.MappingResult) string {
	if res.SourceResource == nil {
		return "HTTP"
	}

	resourceType := strings.ToLower(string(res.SourceResource.Type))

	switch {
	case strings.Contains(resourceType, "network") || strings.Contains(resourceType, "nlb"):
		return "TCP"
	case strings.Contains(resourceType, "application") || strings.Contains(resourceType, "alb"):
		return "HTTP"
	default:
		return "HTTP"
	}
}
