/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Basic health check
         * @description Returns a simple health status. Use this for basic availability checks.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detailed health check
         * @description Returns detailed health status including dependencies, version, and system info.
         */
        get: operations["getHealthDetailed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Kubernetes readiness probe endpoint.
         */
        get: operations["getHealthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Kubernetes liveness probe endpoint.
         */
        get: operations["getHealthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticate with username and password to obtain a session token.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User logout
         * @description Invalidate the current session and clear cookies.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Get information about the currently authenticated user.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password
         * @description Change the password for the currently authenticated user.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migrate/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze infrastructure
         * @description Parse infrastructure-as-code files and return discovered resources.
         *     Supports Terraform, CloudFormation, and ARM templates.
         */
        post: operations["analyzeInfrastructure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migrate/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Docker Compose stack
         * @description Generate a Docker Compose stack from analyzed resources.
         */
        post: operations["generateStack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migrate/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download stack as ZIP
         * @description Generate and download a complete stack as a ZIP file.
         */
        post: operations["downloadStack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set storage credentials
         * @description Store S3/MinIO credentials for the current session.
         */
        post: operations["setStorageCredentials"];
        /**
         * Delete storage credentials
         * @description Remove stored storage credentials for the current session.
         */
        delete: operations["deleteStorageCredentials"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set database credentials
         * @description Store PostgreSQL credentials for the current session.
         */
        post: operations["setDatabaseCredentials"];
        /**
         * Delete database credentials
         * @description Remove stored database credentials for the current session.
         */
        delete: operations["deleteDatabaseCredentials"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List containers
         * @description List all Docker containers in a stack.
         */
        get: operations["listContainers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/containers/{name}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get container logs
         * @description Retrieve logs from a Docker container.
         */
        get: operations["getContainerLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/containers/{name}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart container
         * @description Restart a Docker container.
         */
        post: operations["restartContainer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/containers/{name}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop container
         * @description Stop a running Docker container.
         */
        post: operations["stopContainer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/containers/{name}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start container
         * @description Start a stopped Docker container.
         */
        post: operations["startContainer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/storage/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List buckets
         * @description List all S3-compatible storage buckets.
         */
        get: operations["listBuckets"];
        put?: never;
        /**
         * Create bucket
         * @description Create a new S3-compatible storage bucket.
         */
        post: operations["createBucket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/storage/buckets/{bucket}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete bucket
         * @description Delete an empty S3-compatible storage bucket.
         */
        delete: operations["deleteBucket"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/storage/buckets/{bucket}/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List objects
         * @description List objects in a bucket with optional prefix filter.
         */
        get: operations["listObjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/storage/buckets/{bucket}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload file
         * @description Upload a file to a bucket.
         */
        post: operations["uploadObject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/storage/buckets/{bucket}/download/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download file
         * @description Download a file from a bucket.
         */
        get: operations["downloadObject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/storage/buckets/{bucket}/objects/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete object
         * @description Delete an object from a bucket.
         */
        delete: operations["deleteObject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/storage/buckets/{bucket}/presign/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get presigned URL
         * @description Generate a presigned URL for direct object access (valid for 15 minutes).
         */
        get: operations["getPresignedUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/database/databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List databases
         * @description List all PostgreSQL databases.
         */
        get: operations["listDatabases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/database/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tables
         * @description List all tables in a schema.
         */
        get: operations["listTables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/database/tables/{table}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get table schema
         * @description Get column definitions for a table.
         */
        get: operations["getTableSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/database/tables/{table}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get table data
         * @description Retrieve data from a table.
         */
        get: operations["getTableData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stacks/{stackId}/database/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute SQL query
         * @description Execute a SQL query against the database.
         *     By default, queries are executed in read-only mode.
         */
        post: operations["executeQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description Error message */
            error: string;
            /** @description Error code */
            code?: string;
        };
        StatusResponse: {
            status: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "healthy" | "degraded" | "unhealthy";
        };
        DetailedHealthResponse: {
            /** @enum {string} */
            status: "healthy" | "degraded" | "unhealthy";
            version?: string;
            uptime?: string;
            dependencies?: {
                [key: string]: components["schemas"]["DependencyStatus"];
            };
            system?: components["schemas"]["SystemInfo"];
        };
        DependencyStatus: {
            /** @enum {string} */
            status?: "healthy" | "degraded" | "unhealthy";
            latency?: string;
            error?: string;
        };
        SystemInfo: {
            go_version?: string;
            num_goroutine?: number;
            num_cpu?: number;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            /** @description Session token */
            token?: string;
            username?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        UserInfo: {
            username?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            old_password: string;
            /** Format: password */
            new_password: string;
        };
        AnalyzeRequest: {
            /**
             * @description Infrastructure-as-code format
             * @enum {string}
             */
            type: "terraform" | "cloudformation" | "arm";
            /** @description File content to analyze */
            content: string;
        };
        AnalyzeResponse: {
            resources?: components["schemas"]["ResourceInfo"][];
            warnings?: string[];
            /** @description Detected cloud provider */
            provider?: string;
        };
        ResourceInfo: {
            id?: string;
            name?: string;
            type?: string;
            category?: string;
            dependencies?: string[];
            tags?: {
                [key: string]: string;
            };
        };
        GenerateRequest: {
            resources: components["schemas"]["ResourceInfo"][];
            options?: components["schemas"]["GenerateOptions"];
        };
        GenerateOptions: {
            /**
             * @description Enable high availability configuration
             * @default false
             */
            ha: boolean;
            /**
             * @description Include data migration scripts
             * @default false
             */
            include_migration: boolean;
            /**
             * @description Include monitoring configuration
             * @default false
             */
            include_monitoring: boolean;
            /** @description Domain name for services */
            domain?: string;
        };
        GenerateResponse: {
            /** @description Docker Compose YAML content */
            compose?: string;
            /** @description Generated shell scripts */
            scripts?: {
                [key: string]: string;
            };
            /** @description Generated documentation (README) */
            docs?: string;
            /** @description Base64-encoded ZIP file (optional) */
            zip_base64?: string;
        };
        StorageCredentials: {
            /** @description S3/MinIO endpoint (default localhost:9000) */
            endpoint?: string;
            access_key: string;
            /** Format: password */
            secret_key: string;
        };
        DatabaseCredentials: {
            /** @description Database host (default localhost) */
            host?: string;
            /** @description Database port (default 5432) */
            port?: number;
            /** @description Database name (default postgres) */
            database?: string;
            user: string;
            /** Format: password */
            password: string;
            /**
             * @default disable
             * @enum {string}
             */
            ssl_mode: "disable" | "require" | "verify-ca" | "verify-full";
        };
        ContainerListResponse: {
            containers?: components["schemas"]["ContainerInfo"][];
            count?: number;
        };
        ContainerInfo: {
            id?: string;
            name?: string;
            image?: string;
            status?: string;
            /** @enum {string} */
            state?: "running" | "exited" | "paused" | "created" | "restarting" | "removing" | "dead";
            ports?: components["schemas"]["PortBinding"][];
            /** Format: date-time */
            created?: string;
            labels?: {
                [key: string]: string;
            };
        };
        PortBinding: {
            host_port?: string;
            container_port?: string;
            /** @enum {string} */
            protocol?: "tcp" | "udp";
        };
        BucketListResponse: {
            buckets?: components["schemas"]["BucketInfo"][];
            count?: number;
        };
        BucketInfo: {
            name?: string;
            /** Format: date-time */
            created?: string;
            region?: string;
        };
        ObjectListResponse: {
            objects?: components["schemas"]["ObjectInfo"][];
            count?: number;
            bucket?: string;
            prefix?: string;
        };
        ObjectInfo: {
            key?: string;
            /** Format: int64 */
            size?: number;
            /** Format: date-time */
            last_modified?: string;
            content_type?: string;
            is_dir?: boolean;
        };
        TableListResponse: {
            tables?: components["schemas"]["TableInfo"][];
            count?: number;
            schema?: string;
        };
        TableInfo: {
            schema?: string;
            name?: string;
            type?: string;
            owner?: string;
            /** Format: int64 */
            row_count?: number;
            size?: string;
        };
        TableSchemaResponse: {
            columns?: components["schemas"]["ColumnInfo"][];
            table?: string;
            schema?: string;
        };
        ColumnInfo: {
            name?: string;
            type?: string;
            nullable?: boolean;
            default?: string | null;
            primary_key?: boolean;
        };
        QueryRequest: {
            /** @description SQL query to execute */
            query: string;
            /**
             * @description Execute in read-only mode (default true)
             * @default true
             */
            read_only: boolean;
        };
        QueryResult: {
            columns?: string[];
            rows?: unknown[][];
            row_count?: number;
            /** @description Query execution time */
            duration?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Stack identifier (use "default" for the default stack) */
        stackId: string;
        /** @description Container name */
        containerName: string;
        /** @description Bucket name */
        bucketName: string;
        /** @description Table name */
        tableName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "healthy"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getHealthDetailed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "healthy",
                     *       "version": "1.0.0",
                     *       "uptime": "2h30m15s",
                     *       "dependencies": {
                     *         "docker": {
                     *           "status": "healthy",
                     *           "latency": "5ms"
                     *         }
                     *       },
                     *       "system": {
                     *         "go_version": "go1.21.0",
                     *         "num_goroutine": 12,
                     *         "num_cpu": 8
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["DetailedHealthResponse"];
                };
            };
            /** @description Service is unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedHealthResponse"];
                };
            };
        };
    };
    getHealthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ready */
                        status?: string;
                    };
                };
            };
        };
    };
    getHealthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example alive */
                        status?: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "username": "admin",
                 *       "password": "secret123"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    /** @description Session cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "token": "abc123...",
                     *       "username": "admin",
                     *       "expires_at": "2024-01-15T12:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example logged out */
                        status?: string;
                    };
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "username": "admin",
                     *       "expires_at": "2024-01-15T12:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example password changed */
                        status?: string;
                    };
                };
            };
            /** @description Invalid password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyzeInfrastructure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "type": "terraform",
                 *       "content": "resource \"aws_s3_bucket\" \"example\" {\n  bucket = \"my-bucket\"\n}\n"
                 *     }
                 */
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Analysis results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Parse error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generateStack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Generated stack */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    downloadStack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description ZIP file containing stack */
            200: {
                headers: {
                    /** @description Suggested filename */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setStorageCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageCredentials"];
            };
        };
        responses: {
            /** @description Credentials stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example credentials stored */
                        status?: string;
                    };
                };
            };
            /** @description Invalid credentials */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteStorageCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credentials deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example credentials deleted */
                        status?: string;
                    };
                };
            };
        };
    };
    setDatabaseCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatabaseCredentials"];
            };
        };
        responses: {
            /** @description Credentials stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example credentials stored */
                        status?: string;
                    };
                };
            };
            /** @description Invalid credentials */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteDatabaseCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credentials deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example credentials deleted */
                        status?: string;
                    };
                };
            };
        };
    };
    listContainers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of containers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerListResponse"];
                };
            };
            /** @description Invalid stack ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getContainerLogs: {
        parameters: {
            query?: {
                /** @description Number of log lines to retrieve (1-10000, default 100) */
                tail?: number;
            };
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
                /** @description Container name */
                name: components["parameters"]["containerName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Container logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Log content */
                        logs?: string;
                    };
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restartContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
                /** @description Container name */
                name: components["parameters"]["containerName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Container restarted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "restarted"
                     *     }
                     */
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Invalid container name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stopContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
                /** @description Container name */
                name: components["parameters"]["containerName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Container stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "stopped"
                     *     }
                     */
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    startContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
                /** @description Container name */
                name: components["parameters"]["containerName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Container started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "started"
                     *     }
                     */
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    listBuckets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of buckets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketListResponse"];
                };
            };
            /** @description Storage connection failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createBucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Bucket name (3-63 chars, lowercase)
                     * @example my-bucket
                     */
                    name: string;
                };
            };
        };
        responses: {
            /** @description Bucket created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example created */
                        status?: string;
                        /** @example my-bucket */
                        name?: string;
                    };
                };
            };
            /** @description Invalid bucket name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteBucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
                /** @description Bucket name */
                bucket: components["parameters"]["bucketName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bucket deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example deleted */
                        status?: string;
                        name?: string;
                    };
                };
            };
        };
    };
    listObjects: {
        parameters: {
            query?: {
                /** @description Filter objects by prefix */
                prefix?: string;
            };
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
                /** @description Bucket name */
                bucket: components["parameters"]["bucketName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of objects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectListResponse"];
                };
            };
        };
    };
    uploadObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
                /** @description Bucket name */
                bucket: components["parameters"]["bucketName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description File to upload
                     */
                    file: string;
                    /** @description Object key (defaults to filename) */
                    key?: string;
                };
            };
        };
        responses: {
            /** @description File uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example uploaded */
                        status?: string;
                        bucket?: string;
                        key?: string;
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    downloadObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
                /** @description Bucket name */
                bucket: components["parameters"]["bucketName"];
                /** @description Object key (path to file) */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content */
            200: {
                headers: {
                    /** @description Suggested filename */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Object not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
                /** @description Bucket name */
                bucket: components["parameters"]["bucketName"];
                /** @description Object key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Object deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "deleted"
                     *     }
                     */
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    getPresignedUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
                /** @description Bucket name */
                bucket: components["parameters"]["bucketName"];
                /** @description Object key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presigned URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uri
                         * @description Presigned URL valid for 15 minutes
                         */
                        url?: string;
                    };
                };
            };
        };
    };
    listDatabases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of databases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        databases?: string[];
                        count?: number;
                    };
                };
            };
            /** @description Database connection failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listTables: {
        parameters: {
            query?: {
                /** @description Schema name (default "public") */
                schema?: string;
            };
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tables */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableListResponse"];
                };
            };
        };
    };
    getTableSchema: {
        parameters: {
            query?: {
                /** @description Schema name (default "public") */
                schema?: string;
            };
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
                /** @description Table name */
                table: components["parameters"]["tableName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Table schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableSchemaResponse"];
                };
            };
        };
    };
    getTableData: {
        parameters: {
            query?: {
                /** @description Schema name (default "public") */
                schema?: string;
                /** @description Maximum rows to return (1-1000, default 100) */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
                /** @description Table name */
                table: components["parameters"]["tableName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Table data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResult"];
                };
            };
        };
    };
    executeQuery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stack identifier (use "default" for the default stack) */
                stackId: components["parameters"]["stackId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "query": "SELECT * FROM users LIMIT 10",
                 *       "read_only": true
                 *     }
                 */
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Query results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResult"];
                };
            };
            /** @description Invalid query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
