// Package scaleway provides networking resource generation for Scaleway.
package scaleway

import (
	"bytes"
	"fmt"

	"github.com/homeport/homeport/internal/domain/generator"
	"github.com/homeport/homeport/internal/domain/mapper"
)

// GenerateNetworkingTF generates the networking Terraform configuration for Scaleway.
func GenerateNetworkingTF(vpcs, loadBalancers, dns []*mapper.MappingResult, config *generator.TargetConfig, zone string) string {
	var buf bytes.Buffer

	buf.WriteString("# Scaleway Networking Resources\n")
	buf.WriteString("# Generated by Homeport\n\n")

	projectName := "homeport"
	if config.ProjectName != "" {
		projectName = sanitizeName(config.ProjectName)
	}

	_ = vpcs        // TODO: Use VPC resources
	_ = loadBalancers // TODO: Use load balancer resources
	_ = dns         // TODO: Use DNS resources
	_ = zone        // TODO: Use zone

	// VPC Private Network
	buf.WriteString(generateVPCResource(projectName))

	// Public Gateway (optional, for internet access)
	buf.WriteString(generateGatewayResources(projectName))

	// Security Groups
	buf.WriteString(generateSecurityGroupResources(projectName))

	return buf.String()
}

func generateVPCResource(projectName string) string {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf(`# VPC Private Network
resource "scaleway_vpc_private_network" "main" {
  name   = "%s-vpc"
  region = var.scw_region

  tags = local.common_tags
}

`, projectName))

	return buf.String()
}

func generateGatewayResources(projectName string) string {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf(`# Public Gateway for Internet Access
resource "scaleway_vpc_public_gateway_ip" "main" {
  zone = var.scw_zone
}

resource "scaleway_vpc_public_gateway" "main" {
  name            = "%s-gateway"
  type            = "VPC-GW-S"
  ip_id           = scaleway_vpc_public_gateway_ip.main.id
  bastion_enabled = true
  zone            = var.scw_zone

  tags = local.common_tags
}

# DHCP for private network
resource "scaleway_vpc_public_gateway_dhcp" "main" {
  subnet              = "10.0.1.0/24"
  push_default_route  = true
  push_dns_server     = true
  dns_servers_override = ["1.1.1.1", "8.8.8.8"]
  zone                = var.scw_zone
}

# Connect gateway to private network
resource "scaleway_vpc_gateway_network" "main" {
  gateway_id          = scaleway_vpc_public_gateway.main.id
  private_network_id  = scaleway_vpc_private_network.main.id
  dhcp_id             = scaleway_vpc_public_gateway_dhcp.main.id
  enable_masquerade   = true
  cleanup_dhcp        = true
  zone                = var.scw_zone
}

`, projectName))

	return buf.String()
}

func generateSecurityGroupResources(projectName string) string {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf(`# Security Group for Web/App Servers
resource "scaleway_instance_security_group" "web" {
  name                    = "%s-web-sg"
  zone                    = var.scw_zone
  inbound_default_policy  = "drop"
  outbound_default_policy = "accept"

  # SSH
  inbound_rule {
    action   = "accept"
    protocol = "TCP"
    port     = 22
  }

  # HTTP
  inbound_rule {
    action   = "accept"
    protocol = "TCP"
    port     = 80
  }

  # HTTPS
  inbound_rule {
    action   = "accept"
    protocol = "TCP"
    port     = 443
  }

  # ICMP (ping)
  inbound_rule {
    action   = "accept"
    protocol = "ICMP"
  }
}

# Security Group for Database Servers
resource "scaleway_instance_security_group" "db" {
  name                    = "%s-db-sg"
  zone                    = var.scw_zone
  inbound_default_policy  = "drop"
  outbound_default_policy = "accept"

  # SSH from internal only
  inbound_rule {
    action    = "accept"
    protocol  = "TCP"
    port      = 22
    ip_range  = "10.0.0.0/8"
  }

  # PostgreSQL
  inbound_rule {
    action    = "accept"
    protocol  = "TCP"
    port      = 5432
    ip_range  = "10.0.0.0/8"
  }

  # MySQL
  inbound_rule {
    action    = "accept"
    protocol  = "TCP"
    port      = 3306
    ip_range  = "10.0.0.0/8"
  }

  # Redis
  inbound_rule {
    action    = "accept"
    protocol  = "TCP"
    port      = 6379
    ip_range  = "10.0.0.0/8"
  }
}

`, projectName, projectName))

	return buf.String()
}

// sanitizeName converts a name to a valid Terraform resource name.
func sanitizeName(name string) string {
	// Replace invalid characters with underscores
	result := make([]byte, 0, len(name))
	for i := 0; i < len(name); i++ {
		c := name[i]
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
			result = append(result, c)
		} else {
			result = append(result, '_')
		}
	}
	return string(result)
}
