// Package scaleway generates Terraform configurations for Scaleway cloud platform.
package scaleway

import (
	"bytes"
	"fmt"
	"time"

	"github.com/homeport/homeport/internal/domain/generator"
	"github.com/homeport/homeport/internal/domain/mapper"
)

// GenerateStorageTF generates Terraform configuration for storage resources.
// This includes Object Storage (S3-compatible) and Block Storage.
func GenerateStorageTF(objectStorage, blockStorage []*mapper.MappingResult, config *generator.TargetConfig, region string) string {
	var buf bytes.Buffer

	buf.WriteString("# Scaleway Storage Resources\n")
	buf.WriteString(fmt.Sprintf("# Generated by Homeport - %s\n\n", time.Now().Format(time.RFC3339)))

	// Generate Object Storage buckets
	if len(objectStorage) > 0 {
		buf.WriteString("# ============================================\n")
		buf.WriteString("# Object Storage Buckets (S3-compatible)\n")
		buf.WriteString("# ============================================\n\n")

		for i, r := range objectStorage {
			name := SanitizeTFName(r.SourceResourceName)
			if name == "" {
				name = fmt.Sprintf("bucket_%d", i)
			}

			displayName := SanitizeName(r.SourceResourceName)
			if displayName == "" {
				displayName = fmt.Sprintf("bucket-%d", i)
			}

			buf.WriteString(fmt.Sprintf("# Bucket: %s (from %s)\n", r.SourceResourceName, r.SourceResourceType))

			buf.WriteString(fmt.Sprintf(`resource "scaleway_object_bucket" "%s" {
  name   = "${local.project_name}-%s"
  region = var.scw_region

  # Access control
  acl = "private"

  # Versioning
  versioning {
    enabled = var.bucket_versioning
  }

  # CORS configuration for web access
  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "PUT", "POST", "DELETE", "HEAD"]
    allowed_origins = ["*"]
    max_age_seconds = 3600
  }

  # Lifecycle rules
  dynamic "lifecycle_rule" {
    for_each = var.bucket_lifecycle_days > 0 ? [1] : []
    content {
      enabled = true
      prefix  = ""

      transition {
        days          = var.bucket_lifecycle_days
        storage_class = "GLACIER"
      }

      expiration {
        days = var.bucket_lifecycle_days * 4
      }

      # Clean up incomplete multipart uploads
      abort_incomplete_multipart_upload_days = 7
    }
  }

  tags = {
    managed_by  = "homeport"
    project     = local.project_name
    environment = var.environment
    source      = "%s"
  }
}

`, name, displayName, r.SourceResourceType))

			// Create bucket policy for secure access
			buf.WriteString(fmt.Sprintf(`resource "scaleway_object_bucket_policy" "%s" {
  bucket = scaleway_object_bucket.%s.name
  region = var.scw_region

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "DenyInsecureTransport"
        Effect    = "Deny"
        Principal = "*"
        Action    = "s3:*"
        Resource = [
          scaleway_object_bucket.%s.name,
          "${scaleway_object_bucket.%s.name}/*"
        ]
        Condition = {
          Bool = {
            "aws:SecureTransport" = "false"
          }
        }
      }
    ]
  })
}

`, name, name, name, name))

			// For HA: Enable cross-region replication
			if config.HALevel.RequiresMultiServer() {
				buf.WriteString(fmt.Sprintf(`# Backup bucket for disaster recovery
resource "scaleway_object_bucket" "%s_backup" {
  name   = "${local.project_name}-%s-backup"
  region = var.scw_region == "fr-par" ? "nl-ams" : "fr-par"  # Different region

  acl = "private"

  versioning {
    enabled = true
  }

  tags = {
    managed_by  = "homeport"
    project     = local.project_name
    environment = var.environment
    purpose     = "backup"
    source      = "%s"
  }
}

`, name, displayName, r.SourceResourceType))
			}
		}
	}

	// Generate Block Storage volumes
	if len(blockStorage) > 0 {
		buf.WriteString("# ============================================\n")
		buf.WriteString("# Block Storage Volumes\n")
		buf.WriteString("# ============================================\n\n")

		for i, r := range blockStorage {
			name := SanitizeTFName(r.SourceResourceName)
			if name == "" {
				name = fmt.Sprintf("volume_%d", i)
			}

			displayName := SanitizeName(r.SourceResourceName)
			if displayName == "" {
				displayName = fmt.Sprintf("volume-%d", i)
			}

			// Determine volume size from source (default 50GB)
			volumeSize := 50
			if r.SourceResource != nil {
				if size, ok := r.SourceResource.Config["size_gb"]; ok {
					if sizeInt, ok := size.(int); ok && sizeInt > 0 {
						volumeSize = sizeInt
					}
				}
			}

			buf.WriteString(fmt.Sprintf("# Block Volume: %s (from %s)\n", r.SourceResourceName, r.SourceResourceType))

			buf.WriteString(fmt.Sprintf(`resource "scaleway_block_volume" "%s" {
  name       = "${local.project_name}-%s"
  size_in_gb = %d
  zone       = var.scw_zone

  # Performance options
  iops = 5000  # Max IOPS for the volume

  tags = local.common_tags
}

`, name, displayName, volumeSize))

			// Snapshot for backup if HA is enabled
			if config.HALevel.Level() >= 1 {
				buf.WriteString(fmt.Sprintf(`# Snapshot schedule for backup
resource "scaleway_block_snapshot" "%s_snapshot" {
  name      = "${local.project_name}-%s-snapshot"
  volume_id = scaleway_block_volume.%s.id
  zone      = var.scw_zone

  tags = concat(local.common_tags, ["snapshot"])

  lifecycle {
    create_before_destroy = true
  }
}

`, name, displayName, name))
			}
		}

		// Create a shared volume for HA setups
		if config.HALevel.RequiresMultiServer() && len(blockStorage) > 0 {
			buf.WriteString(`# ============================================
# Shared Storage for HA
# ============================================

resource "scaleway_block_volume" "shared_data" {
  name       = "${local.project_name}-shared-data"
  size_in_gb = 100
  zone       = var.scw_zone
  iops       = 5000

  tags = concat(local.common_tags, ["shared"])
}

`)
		}
	}

	// Add IAM for bucket access
	if len(objectStorage) > 0 {
		buf.WriteString("# ============================================\n")
		buf.WriteString("# Storage Access (IAM Application)\n")
		buf.WriteString("# ============================================\n\n")

		buf.WriteString(`# Application for programmatic access to Object Storage
resource "scaleway_iam_application" "storage_access" {
  name        = "${local.project_name}-storage-app"
  description = "Application for Object Storage access"
}

resource "scaleway_iam_api_key" "storage_access" {
  application_id = scaleway_iam_application.storage_access.id
  description    = "API key for Object Storage access"
}

# Store API key in outputs (sensitive)
output "storage_access_key_id" {
  description = "Access key ID for Object Storage"
  value       = scaleway_iam_api_key.storage_access.access_key
  sensitive   = true
}

output "storage_secret_key" {
  description = "Secret key for Object Storage"
  value       = scaleway_iam_api_key.storage_access.secret_key
  sensitive   = true
}

`)
	}

	return buf.String()
}
