import { useState } from 'react';
import { Link } from 'react-router-dom';
import type { AWSOperationService, AWSOperationServiceState, AWSOperationWorkspace } from '@/lib/aws-operations-types';

function fallbackService(key: string, state: AWSOperationServiceState): AWSOperationService { return { service: key, display_name: key, target: 'local', family: 'Other', panel_kind: 'resource-list', ...state }; }
export function AWSServiceGrid({ workspace, services }: { workspace: AWSOperationWorkspace; services?: AWSOperationService[] }) {
  const [filter, setFilter] = useState('');
  const fallbackCatalogue = Object.entries(workspace.services).flatMap(([key, state]) => state ? [fallbackService(key, state)] : []);
  const catalogue = (services ?? fallbackCatalogue).filter((service) => `${service.display_name} ${service.service} ${service.family}`.toLowerCase().includes(filter.toLowerCase()));
  const groups = catalogue.reduce<Record<string, AWSOperationService[]>>((result, service) => { (result[service.family] ??= []).push(service); return result; }, {});
  return <div className="space-y-6"><label className="block text-sm font-medium" htmlFor="aws-service-filter">Filter services<input id="aws-service-filter" type="search" className="mt-1 block w-full rounded-md border bg-background px-3 py-2" value={filter} onChange={(event) => setFilter(event.target.value)} /></label>{Object.entries(groups).sort(([left], [right]) => left.localeCompare(right)).map(([family, entries]) => <section key={family} className="space-y-3"><h2 className="text-lg font-semibold">{family}</h2><div className="grid gap-4 md:grid-cols-2">{entries.sort((left, right) => left.display_name.localeCompare(right.display_name)).map((service) => { const count = workspace.bindings.filter((binding) => binding.service === service.service).length; return <div key={service.service} className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-semibold">{service.display_name}</h3><span className={service.status === 'available' ? 'badge-success' : 'badge-warning'}>{service.status === 'available' ? 'Ready' : service.status}</span></div><p className="mt-3 text-sm text-muted-foreground">{service.reason || `Target: ${service.target} · ${count} migrated resource${count === 1 ? '' : 's'} · ${service.capabilities.join(', ') || 'read-only'}`}</p><Link to={`/aws/${encodeURIComponent(service.service)}`} className="mt-5 inline-flex rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground">Open {service.display_name} operations</Link></div>; })}</div></section>)}</div>;
}
