// Package hetzner provides networking resource generation for Hetzner Cloud.
package hetzner

import (
	"bytes"
	"fmt"

	"github.com/homeport/homeport/internal/domain/generator"
)

// GenerateNetworkingTF generates the networking Terraform configuration for Hetzner.
func GenerateNetworkingTF(categorized *CategorizedResults, config *generator.TargetConfig, location string) string {
	var buf bytes.Buffer

	buf.WriteString("# Hetzner Cloud Networking Configuration\n")
	buf.WriteString("# Generated by Homeport\n\n")

	// Generate VPC/Network
	buf.WriteString(generateNetworkResource(config, location))

	// Generate subnets
	buf.WriteString(generateSubnetResources(config))

	// Generate firewall rules
	buf.WriteString(generateFirewallResources(config))

	// Generate load balancer if needed
	if len(categorized.Network) > 0 {
		buf.WriteString(generateLoadBalancerResources(config, location))
	}

	return buf.String()
}

func generateNetworkResource(config *generator.TargetConfig, location string) string {
	var buf bytes.Buffer

	projectName := "homeport"
	if config.ProjectName != "" {
		projectName = SanitizeName(config.ProjectName)
	}

	buf.WriteString(fmt.Sprintf(`# Private Network
resource "hcloud_network" "main" {
  name     = "%s-network"
  ip_range = "10.0.0.0/16"
  labels = {
    project = "%s"
  }
}

`, projectName, projectName))

	return buf.String()
}

func generateSubnetResources(config *generator.TargetConfig) string {
	var buf bytes.Buffer

	projectName := "homeport"
	if config.ProjectName != "" {
		projectName = SanitizeName(config.ProjectName)
	}

	// Note: projectName is extracted but not used in subnet resources
	// as they reference the network by resource name
	_ = projectName

	buf.WriteString(`# App Subnet
resource "hcloud_network_subnet" "app" {
  type         = "cloud"
  network_id   = hcloud_network.main.id
  network_zone = "eu-central"
  ip_range     = "10.0.1.0/24"
}

# Database Subnet
resource "hcloud_network_subnet" "db" {
  type         = "cloud"
  network_id   = hcloud_network.main.id
  network_zone = "eu-central"
  ip_range     = "10.0.2.0/24"
}

# Management Subnet
resource "hcloud_network_subnet" "mgmt" {
  type         = "cloud"
  network_id   = hcloud_network.main.id
  network_zone = "eu-central"
  ip_range     = "10.0.0.0/24"
}

`)

	return buf.String()
}

func generateFirewallResources(config *generator.TargetConfig) string {
	var buf bytes.Buffer

	projectName := "homeport"
	if config.ProjectName != "" {
		projectName = SanitizeName(config.ProjectName)
	}

	buf.WriteString(fmt.Sprintf(`# Firewall for App Servers
resource "hcloud_firewall" "app" {
  name = "%s-app-fw"

  # SSH access
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "22"
    source_ips = ["0.0.0.0/0", "::/0"]
  }

  # HTTP
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "80"
    source_ips = ["0.0.0.0/0", "::/0"]
  }

  # HTTPS
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "443"
    source_ips = ["0.0.0.0/0", "::/0"]
  }

  # ICMP (ping)
  rule {
    direction  = "in"
    protocol   = "icmp"
    source_ips = ["0.0.0.0/0", "::/0"]
  }

  labels = {
    project = "%s"
  }
}

# Firewall for Database Servers
resource "hcloud_firewall" "db" {
  name = "%s-db-fw"

  # SSH access (restricted to internal)
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "22"
    source_ips = ["10.0.0.0/16"]
  }

  # PostgreSQL
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "5432"
    source_ips = ["10.0.0.0/16"]
  }

  # MySQL
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "3306"
    source_ips = ["10.0.0.0/16"]
  }

  # Redis
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "6379"
    source_ips = ["10.0.0.0/16"]
  }

  labels = {
    project = "%s"
  }
}

`, projectName, projectName, projectName, projectName))

	return buf.String()
}

func generateLoadBalancerResources(config *generator.TargetConfig, location string) string {
	var buf bytes.Buffer

	projectName := "homeport"
	if config.ProjectName != "" {
		projectName = SanitizeName(config.ProjectName)
	}

	buf.WriteString(fmt.Sprintf(`# Load Balancer
resource "hcloud_load_balancer" "main" {
  name               = "%s-lb"
  load_balancer_type = "lb11"
  location           = "%s"

  labels = {
    project = "%s"
  }
}

# Load Balancer Network Attachment
resource "hcloud_load_balancer_network" "main" {
  load_balancer_id = hcloud_load_balancer.main.id
  network_id       = hcloud_network.main.id
  ip               = "10.0.1.254"
}

# HTTP Service
resource "hcloud_load_balancer_service" "http" {
  load_balancer_id = hcloud_load_balancer.main.id
  protocol         = "http"
  listen_port      = 80
  destination_port = 80

  health_check {
    protocol = "http"
    port     = 80
    interval = 15
    timeout  = 10
    retries  = 3
    http {
      path         = "/"
      status_codes = ["2??", "3??"]
    }
  }
}

# HTTPS Service
resource "hcloud_load_balancer_service" "https" {
  load_balancer_id = hcloud_load_balancer.main.id
  protocol         = "https"
  listen_port      = 443
  destination_port = 443

  health_check {
    protocol = "http"
    port     = 80
    interval = 15
    timeout  = 10
    retries  = 3
    http {
      path         = "/"
      status_codes = ["2??", "3??"]
    }
  }
}

# Load Balancer Targets
resource "hcloud_load_balancer_target" "app" {
  count            = length(hcloud_server.app)
  type             = "server"
  load_balancer_id = hcloud_load_balancer.main.id
  server_id        = hcloud_server.app[count.index].id
  use_private_ip   = true
}

`, projectName, location, projectName))

	return buf.String()
}
