import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { LambdaResourceDetail } from '@/components/aws-operations/LambdaResourceDetail';
import { LambdaResourceList } from '@/components/aws-operations/LambdaResourceList';
import { deleteAWSLambda, invokeAWSLambda, listAWSOperationResources, listAWSOperationsWorkspaces } from '@/lib/aws-operations-api';
import type { AWSLambdaResource } from '@/lib/aws-operations-types';
export function AWSLambda() {
  const client = useQueryClient(); const [selected, setSelected] = useState<AWSLambdaResource | null>(null); const [invokeTarget, setInvokeTarget] = useState<AWSLambdaResource | null>(null); const [payload, setPayload] = useState('{}'); const [filter, setFilter] = useState('');
  const workspaceQuery = useQuery({ queryKey: ['aws-operations', 'workspaces'], queryFn: listAWSOperationsWorkspaces });
  const workspace = workspaceQuery.data?.workspaces.find((w) => w.services.lambda?.status === 'available'); const state = workspace?.services.lambda;
  const resources = useQuery({ queryKey: ['aws-operations', workspace?.id, 'lambda'], queryFn: () => listAWSOperationResources<AWSLambdaResource>(workspace!.id, 'lambda'), enabled: !!workspace });
  const invoke = useMutation({ mutationFn: ({ id, body }: { id: string; body: unknown }) => invokeAWSLambda(workspace!.id, id, body), onSuccess: () => toast.success('Invocation completed'), onError: (error) => toast.error('Invocation failed', { description: error instanceof Error ? error.message : 'Local backend remains unchanged.' }) });
  const remove = useMutation({ mutationFn: (id: string) => deleteAWSLambda(workspace!.id, id), onSuccess: () => { setSelected(null); client.invalidateQueries({ queryKey: ['aws-operations', workspace?.id, 'lambda'] }); toast.success('Function deleted'); }, onError: (error) => toast.error('Delete failed', { description: error instanceof Error ? error.message : 'Unknown error' }) });
  const visible = useMemo(() => (resources.data?.resources || []).filter((item) => `${item.name} ${item.region} ${item.runtime} ${item.status}`.toLowerCase().includes(filter.toLowerCase())), [resources.data, filter]);
  if (!workspaceQuery.isLoading && !workspace) return <p className="text-muted-foreground">Lambda operations are unavailable until Lambda cutover is activated.</p>;
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Lambda operations</h1><p className="text-muted-foreground">Bound local functions for the active post-cutover workspace.</p></div><input className="w-full rounded-md border bg-background px-3 py-2" value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Filter by name, region, runtime, or status" />{resources.isLoading ? <p>Loading functions…</p> : <div className="grid gap-5 lg:grid-cols-2"><LambdaResourceList resources={visible} capabilities={state?.capabilities || []} onSelect={setSelected} onInvoke={setInvokeTarget} />{selected && <LambdaResourceDetail workspaceId={workspace!.id} resource={selected} capabilities={state?.capabilities || []} onDelete={() => { if (window.confirm(`Delete ${selected.name}? This cannot be undone.`)) remove.mutate(selected.id); }} />}</div>}{invokeTarget && <div role="dialog" aria-label="Invoke function" className="fixed inset-0 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-lg rounded-lg bg-background p-5"><h2 className="font-semibold">Invoke {invokeTarget.name}</h2><textarea className="mt-4 h-40 w-full rounded border p-2 font-mono text-sm" value={payload} onChange={(event) => setPayload(event.target.value)} /><div className="mt-4 flex justify-end gap-2"><button onClick={() => setInvokeTarget(null)}>Cancel</button><button className="rounded bg-primary px-3 py-2 text-primary-foreground" onClick={() => { try { invoke.mutate({ id: invokeTarget.id, body: JSON.parse(payload) }); setInvokeTarget(null); } catch { toast.error('Payload must be valid JSON'); } }}>Invoke</button></div></div></div>}</div>;
}
