import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { SQSResourceDetail } from '@/components/aws-operations/SQSResourceDetail';
import { SQSResourceList } from '@/components/aws-operations/SQSResourceList';
import { deleteAWSSQSMessage, listAWSOperationResources, listAWSOperationsWorkspaces, listAWSSQSMessages, purgeAWSSQS, retryAWSSQSMessage } from '@/lib/aws-operations-api';
import type { AWSSQSResource } from '@/lib/aws-operations-types';
export function AWSSQS() {
 const client = useQueryClient(); const [selected, setSelected] = useState<AWSSQSResource | null>(null); const [status, setStatus] = useState('pending'); const [confirmation, setConfirmation] = useState<'purge' | { delete: string } | null>(null); const workspaces = useQuery({ queryKey: ['aws-operations', 'workspaces'], queryFn: listAWSOperationsWorkspaces }); const workspace = workspaces.data?.workspaces.find((w) => w.services.sqs?.status === 'available'); const capabilities = workspace?.services.sqs?.capabilities || [];
 const queues = useQuery({ queryKey: ['aws-operations', workspace?.id, 'sqs'], queryFn: () => listAWSOperationResources<AWSSQSResource>(workspace!.id, 'sqs'), enabled: !!workspace }); const messages = useQuery({ queryKey: ['aws-operations', workspace?.id, 'sqs', selected?.name, status], queryFn: () => listAWSSQSMessages(workspace!.id, selected!.name, status), enabled: !!workspace && !!selected });
 const refresh = () => { client.invalidateQueries({ queryKey: ['aws-operations', workspace?.id, 'sqs'] }); client.invalidateQueries({ queryKey: ['aws-operations', workspace?.id, 'sqs', selected?.name] }); }; const retry = useMutation({ mutationFn: (id: string) => retryAWSSQSMessage(workspace!.id, selected!.name, id), onSuccess: () => { refresh(); toast.success('Message queued for retry'); }, onError: () => toast.error('Retry failed') }); const remove = useMutation({ mutationFn: (id: string) => deleteAWSSQSMessage(workspace!.id, selected!.name, id), onSuccess: () => { refresh(); toast.success('Message deleted'); }, onError: () => toast.error('Delete failed') }); const purge = useMutation({ mutationFn: () => purgeAWSSQS(workspace!.id, selected!.name, status), onSuccess: () => { refresh(); toast.success('Messages purged'); }, onError: () => toast.error('Purge failed') });
 if (!workspaces.isLoading && !workspace) { const unavailable = workspaces.data?.workspaces[0]?.services.sqs; return <p className="text-muted-foreground">{unavailable?.reason || 'SQS operations are unavailable until SQS cutover is activated.'}</p>; }
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">SQS operations</h1><p className="text-muted-foreground">Bound local queues for the active post-cutover workspace.</p></div><div className="flex gap-2">{['pending', 'active', 'completed', 'failed'].map((item) => <button key={item} className={`rounded px-3 py-1.5 text-sm ${status === item ? 'bg-primary text-primary-foreground' : 'border'}`} onClick={() => setStatus(item)}>{item}</button>)}</div><div className="grid gap-5 lg:grid-cols-2"><SQSResourceList resources={queues.data?.resources || []} onSelect={setSelected} />{selected && <SQSResourceDetail queue={selected} messages={messages.data?.messages || []} capabilities={capabilities} onRetry={(id) => retry.mutate(id)} onDelete={(id) => setConfirmation({ delete: id })} onPurge={() => setConfirmation('purge')} />}</div>{confirmation && selected && <div role="dialog" aria-label="Confirm queue operation" className="fixed inset-0 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-md rounded-lg bg-background p-5"><h2 className="font-semibold">Confirm operation</h2><p className="mt-2 text-sm text-muted-foreground">{confirmation === 'purge' ? `Permanently remove ${status} messages from ${selected.name}?` : 'Permanently remove this message?'}</p><div className="mt-5 flex justify-end gap-2"><button onClick={() => setConfirmation(null)}>Cancel</button><button className="rounded bg-destructive px-3 py-2 text-destructive-foreground" onClick={() => { if (confirmation === 'purge') purge.mutate(); else remove.mutate(confirmation.delete); setConfirmation(null); }}>Confirm</button></div></div></div>}</div>;
}
