package messaging

import (
	"context"
	"strings"
	"testing"

	"github.com/homeport/homeport/internal/domain/mapper"
	"github.com/homeport/homeport/internal/domain/resource"
	domainrunbook "github.com/homeport/homeport/internal/domain/runbook"
)

func TestSESConformanceManagedAToZ(t *testing.T) {
	result, err := NewSESMapper().Map(context.Background(), managedSESFixture())
	if err != nil {
		t.Fatal(err)
	}
	if len(result.ManualSteps) != 0 {
		t.Fatalf("manual steps = %#v, want generated SES migration", result.ManualSteps)
	}
	if result.DockerService.Image != "ghcr.io/postalserver/postal:3" || result.DockerService.Deploy == nil || result.DockerService.Deploy.Replicas < 2 {
		t.Fatalf("service does not provision HA Postal target: %#v", result.DockerService)
	}
	for _, file := range []string{"config/postal/postal.yml", "config/postal/dns-records.txt", "config/postal/app-change.env"} {
		if _, ok := result.Configs[file]; !ok {
			t.Fatalf("missing config %s", file)
		}
	}
	if _, ok := result.Configs["config/postal/signing.key"]; ok {
		t.Fatalf("static DKIM private key should be generated by script, not committed as config")
	}
	appEnv := string(result.Configs["config/postal/app-change.env"])
	for _, want := range []string{"APP_CHANGE_MODE=generated_patch", "SOURCE_SES_IDENTITY=example.com", "TARGET_MAIL_SERVICE=postal", "SMTP_HOST=mail.localhost"} {
		if !strings.Contains(appEnv, want) {
			t.Fatalf("app-change env missing %q:\n%s", want, appEnv)
		}
	}
	dns := string(result.Configs["config/postal/dns-records.txt"])
	for _, want := range []string{"v=spf1", "v=DKIM1", "v=DMARC1", "MX    10 mail.example.com."} {
		if !strings.Contains(dns, want) {
			t.Fatalf("dns records missing %q:\n%s", want, dns)
		}
	}
	for _, file := range []string{"scripts/ses-export.sh", "scripts/postal-setup.sh", "scripts/postal-generate-dkim.sh", "scripts/postal-validate.sh", "scripts/postal-backup.sh", "scripts/postal-cutover.sh"} {
		if _, ok := result.Scripts[file]; !ok {
			t.Fatalf("missing script %s", file)
		}
	}
	dkimScript := string(result.Scripts["scripts/postal-generate-dkim.sh"])
	if strings.Contains(dkimScript, "PLACEHOLDER") || !strings.Contains(dkimScript, "openssl genrsa") {
		t.Fatalf("DKIM script must generate a real key:\n%s", dkimScript)
	}
	for id, stepType := range map[string]domainrunbook.StepType{
		"export-ses-identity":     domainrunbook.StepTypeCommand,
		"provision-postal-mail":   domainrunbook.StepTypeCommand,
		"generate-postal-dkim":    domainrunbook.StepTypeCommand,
		"migrate-ses-mail-config": domainrunbook.StepTypeCommand,
		"validate-postal-mail":    domainrunbook.StepTypeCommand,
		"backup-postal-mail":      domainrunbook.StepTypeCommand,
		"cutover-ses-clients":     domainrunbook.StepTypeAPICall,
		"rollback-ses-source":     domainrunbook.StepTypeRollback,
	} {
		if !hasSESRunbookStep(result, id, stepType) {
			t.Fatalf("missing %s runbook step: %#v", id, result.RunbookSteps)
		}
	}
}

func managedSESFixture() *resource.AWSResource {
	return &resource.AWSResource{
		ID:     "arn:aws:ses:eu-west-1:123456789012:identity/example.com",
		Type:   resource.TypeSESIdentity,
		Name:   "example.com",
		Region: "eu-west-1",
		Config: map[string]interface{}{
			"identity_type":               "DOMAIN",
			"dkim_signing_enabled":        true,
			"verified_for_sending_status": true,
			"mail_from_domain":            "mail.example.com",
			"configuration_set":           "production",
		},
	}
}

func hasSESRunbookStep(result *mapper.MappingResult, id string, stepType domainrunbook.StepType) bool {
	for _, step := range result.RunbookSteps {
		if step.ID == id && step.Type == stepType {
			return true
		}
	}
	return false
}
